### ISSUE TITLE
Can't run command directly for pipx

### ISSUE THREAD

**Issue by matbgn** [lighttigerXIV/ulauncher-terminal-runner-extension#2]
/bin/bash: line 1: x11pygrid: command not found

**Comment by lighttigerXIV** [comment]
What shell and terminal are you using? Or what command are you trying to use?

**Comment by lighttigerXIV** [comment]
> What shell and terminal are you using? Or what command are you trying to use?



> /bin/bash: line 1: x11pygrid: command not found
What shell and terminal are you using? Or what command are you trying to use?

**Comment by lighttigerXIV** [comment]
> /bin/bash: line 1: x11pygrid: command not found

What shell and terminal are you using? Or what command are you trying to use?

**Comment by matbgn** [comment]
bash & gnome-terminal
