### ISSUE TITLE
aslias bug : zsh:1: command not found

### ISSUE THREAD

**Issue by luutuankiet** [lighttigerXIV/ulauncher-terminal-runner-extension#3]
Hi, 

I have set the following alias in .zshrc which launches a script with trailing input passed in as argument. 
`alias {t,tick,task}="~/ticktask/ticktask"`

executing this from terminal runner doesn't seem to work? Got the error `: zsh:1: command not found` if i type in `t test`

please find my setup:
OS : linux mint
bash : zshrc

**Comment by lighttigerXIV** [comment]
> Hi,
> 
> I have set the following alias in .zshrc which launches a script with trailing input passed in as argument. `alias {t,tick,task}="~/ticktask/ticktask"`
> 
> executing this from terminal runner doesn't seem to work? Got the error `: zsh:1: command not found` if i type in `t test`
> 
> please find my setup: OS : linux mint bash : zshrc

I still don't know how to make them work with extension. But i will try

**Comment by lighttigerXIV** [comment]
@luutuankiet I managed to make it work. I only needed to add **-i** in the parameters. I will update the project now.
