### ISSUE TITLE
Empty result and setting to use Konsole terminal.

### ISSUE THREAD

**Issue by matheusunderline** [lighttigerXIV/ulauncher-terminal-runner-extension#4]
Hi again, lighttigerXIV.

I aware that the plugin is old, but can you provide me support about these things, please:

1. By default, the plugin doesn't support Konsole terminal.
Is it the correct way to make support the plugin?

![image](https://github.com/lighttigerXIV/ulauncher-terminal-runner-extension/assets/112908515/02ab4e88-4d8c-4b05-81f5-cd747b519af8)

Is it only need to add the Konsole path to input?

Sorry the shame question, I really do not know how procede...

2. I tried to do the "1." workaround, but when I run the command, it only invokes the Konsole terminal without the command result.

https://github.com/lighttigerXIV/ulauncher-terminal-runner-extension/assets/112908515/e9b51ee3-4445-4fa0-869c-f9952b29aa3a

Thank you.

**Comment by lighttigerXIV** [comment]
I think with konsole you need to use `-e` to run commands instead of `--`

**Comment by matheusunderline** [comment]
Wow, cool, now it is working.

It is mean that the path to the terminal Konsole is right.

All Right, it report may be closed.
